---
# tasks file for ansible-role-win-disable-password-complexity
- name: PasswordPolicy
  win_security_policy:
    section: System Access
    key: PasswordComplexity
    value: 0
  register: passwordcomplexity

- name: Reboot if disabling password complexity requires it requires it
  win_reboot:
  when: passwordcomplexity.reboot_required